### ISSUE TITLE
TS2416 error after upgrade to 7.7.0

### ISSUE THREAD

**Issue by qdoobp** [masvis/angular4-hal#53]
I just updated to version 7.70 and the following error occured during building:
```
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11):
 error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
Time: 6292ms
node_modules/angular4-hal/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): 
error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
chunk {main} main.js, main.js.map (main) 636 bytes [initial] [rendered]
src/app/services/externalconfiguration.service.ts(16,3): error TS2416: 
Property 'getHttp' in type 'ExternalConfigurationService' is not assignable 
to the same property in base type 'ExternalConfigurationHandlerInterface'.
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 92.4 kB [initial] [rendered]
  Type '() => import("node_modules/@angular/common/http/src/client").HttpClient' 
is not assignable to type '() => import("node_modules/angular4-hal/node_modules/@angular/common/http/src/client").HttpClient'.
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
    Type 'import("node_modules/@angular/common/http/src/client").HttpClient' is not assignable to type 'import("node_modules/angular4-hal/node_modules/@angular/common/http/src/client").HttpClient'.
chunk {styles} styles.js, styles.js.map (styles) 900 kB [initial] [rendered]      
Types have separate declarations of a private property 'handler'.
```
I am using Angular 7.2.2. Could this be a compatibility issue between the Angular version 7.1.4? Downgrading to 7.6.5 solves it for me.

Thanks for the help and the great work maintaining this project

**Comment by jefferson-lima** [comment]
I'm having the same issue with Angular 7.0.0.

**Comment by Amirroracle** [comment]
Got this issue as well

**Comment by Tavisco** [comment]
+1 on this using the version 7.8.1 of this library

**Comment by sante85** [comment]
update
